package frc.robot.config;

public class ControlsMap {

  // Controllers
  public static final int DRIVER_PORT = 0;
  public static final int OPERATOR_PORT = 1;

  // XboxOne Joysticks
  public static final int LEFT_STICK_X = 0;
  public static final int LEFT_STICK_Y = 1;
  public static final int LEFT_TRIGGER = 2;
  public static final int RIGHT_TRIGGER = 3;
  public static final int RIGHT_STICK_X = 4;
  public static final int RIGHT_STICK_Y = 5;

  // XboxOne Buttons
  public static final int A = 1;
  public static final int B = 2;
  public static final int X = 3;
  public static final int Y = 4;
  public static final int LB = 5;
  public static final int RB = 6;
  public static final int LOGO_LEFT = 7;
  public static final int LOGO_RIGHT = 8;
  public static final int LEFT_STICK_BUTTON = 9;
  public static final int RIGHT_STICK_BUTTON = 10;

  // POV Buttons
  public static final int up = 0;
  public static final int down = 180;
  public static final int right = 270;
  public static final int left = 90;

  // Deadbands
  public static final double AXIS_DEADBAND = 0.1;
  public static final double ShoulderSpeedControlThreshold = 0.2;
}
